"""empty message

Revision ID: 49891d5e8cc8
Revises: d6d5a13baf4f
Create Date: 2025-04-09 23:44:26.206857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49891d5e8cc8'
down_revision = 'd6d5a13baf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido1', sa.String(length=100), nullable=False),
    sa.Column('apellido2', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacto')
    # ### end Alembic commands ###
