"""empty message

Revision ID: 673e584af5fc
Revises: 452f68439d70
Create Date: 2025-04-09 18:08:51.422776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673e584af5fc'
down_revision = '452f68439d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometros', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lugar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finaliza', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('etapa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('salida', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dificultad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sinpe', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coordinador', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('limite_pago', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parqueo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mascotas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('duchas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('banos', sa.String(length=10), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('banos')
        batch_op.drop_column('duchas')
        batch_op.drop_column('mascotas')
        batch_op.drop_column('parqueo')
        batch_op.drop_column('limite_pago')
        batch_op.drop_column('precio')
        batch_op.drop_column('coordinador')
        batch_op.drop_column('sinpe')
        batch_op.drop_column('dificultad')
        batch_op.drop_column('salida')
        batch_op.drop_column('hora')
        batch_op.drop_column('capacidad')
        batch_op.drop_column('etapa')
        batch_op.drop_column('finaliza')
        batch_op.drop_column('lugar')
        batch_op.drop_column('altura')
        batch_op.drop_column('kilometros')

    # ### end Alembic commands ###
